### ISSUE TITLE
Example 5.12 of Chapter 5: Additional Time Domain Topics in tsa4

### ISSUE THREAD

**Issue by jimmyamp** [nickpoison/tsa4#1]
Dear Nicky Poison,

In the Example 5.12 of Chapter 5: Additional Time Domain Topics
https://github.com/nickpoison/tsa4/blob/master/textRcode.md#chapter-5

The R code command line below:

acf(innov)

has created the error as below.

Error in na.fail.default(as.ts(x)) : missing values in object

I guess the arugment "na.action = na.fail" as default value by stats::acf function may be the cause of the error.

So, I set the arugment "na.action = na.pass" in the command line above as

acf(innov, na.action = na.pass)

to have a display of 3 x 3 plots of acf() as result.

I may be wrong.

Please consider the suggestion in your side to check whether my suggestion is wrong or not.

Thanks in advance.

Best regards,
Jimmy Au

> tsplot(innov) 
> head(innov)  # contains missing values
               u1            u2              u3
1            NA           NA             NA
2            NA           NA             NA
3 -7.986554 -3.401042  -6.244936
4 -3.757739  5.160169  -2.446715
5 -2.455558  6.115729  11.073832
6 -1.188275 -2.249943 -10.914951
> #acf(innov)              # <--------  Error
> acf(innov, na.action = na.pass)
> acf(innov)
Error in na.fail.default(as.ts(x)) : missing values in object
>

**Comment by nickpoison** [comment]
that's correct - done
