### ISSUE TITLE
Wrong ACF code in Example 3.11

### ISSUE THREAD

**Issue by JiaqiLiu** [nickpoison/tsa4#2]
## The problem

The following code of Example 3.11 is inconsistent with the chart shown in left-hand-side of Fig 3.5. 

https://github.com/nickpoison/tsa4/blob/775a7ec6fcf4cbe3fcaf67575060726fc2888bdf/textRcode.md?plain=1#L567-L569

ACF is a list with value of ACF[1] being actually $\rho(0)=1$. That is, the lag values skewed. 

The following figure shows what will be plotted using the code above.

<img width="647" alt="Screen Shot 2023-01-01 at 01 15 23" src="https://user-images.githubusercontent.com/1393871/210166056-433398e6-a689-4d72-b94a-81a970959513.png">

## The fix

Actually ACF chart should be start with index 0. Or, if we just ignore ACF[1] (which is always 1), the code should be:

```
ACF = ARMAacf(ar=c(1.5,-.75), ma=0, 25)[-1]
plot(ACF, type="h", xlab="lag")
abline(h=0)
```

which produces

<img width="649" alt="Screen Shot 2023-01-01 at 01 16 46" src="https://user-images.githubusercontent.com/1393871/210166107-6fb06883-2617-4cc4-81b0-3de31ac129d4.png">

The chart above is exactly Fig 3.5 in the text.

## R version

```
> version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again            
```

**Comment by nickpoison** [comment]
Thanks - 2 options are now given (removing 0 lag as in text or keeping it)
